---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/3/12 10:42
---
ConfigLoadOrder = { completeFirst = {}, completeLast = {} }

function ConfigLoadOrder:GetCompleteFirst()
    return self.completeFirst
end

function ConfigLoadOrder:GetCompleteLast()
    return self.completeLast
end