---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/3/12 14:13
---
package.cpath = package.cpath .. ';C:/Users/dream/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/223.8836.42.plugins/EmmyLua/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966)