---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/3/12 10:34
---
DefaultGameConfig = Class("DefaultGameConfig")

DefaultGameConfig.name = "default"
DefaultGameConfig.config = {}

function DefaultGameConfig:Ctor()

end

function DefaultGameConfig:GetName()
    return self.name
end

function DefaultGameConfig:GetConfig()
    return self.config
end

function DefaultGameConfig:InjectConfig(config)
    self.config = config
end

function DefaultGameConfig:OnAllConfigInjectComplete()

end