---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/3/12 10:32
---

local handbookConfig = Class("handbookConfig", DefaultGameConfig)

handbookConfig.name = "handbook"
handbookConfig.config = {}

function handbookConfig:Ctor()

end

function handbookConfig:OnAllConfigInjectComplete()
    
end

return handbookConfig